### ISSUE TITLE
jump_corr dependency prospectr

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#10]
Hi Dudu, `jump_corr ()` is giving me trouble. It depends on the `library (prospectr)`. When I try to run `jump_corr()` from outside the package I get the following Error message. I think `prospectr` needs to be referenced differently.

* Adding prospectr to Imports
Error: Could not find package root.

Any idea what to do?

**Comment by meireles** [comment]
Will have to look at it later, maybe Tuesday. If the only reason you're using it is to resample and smooth spectra, we're probably better off writing our own. Should be pretty easy.

**Comment by annakat** [comment]
import(prospectr) was missing in NAMESPACE
`@import prospectr` added to in script
