### ISSUE TITLE
`plot (..., add=T)` not working

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#11]
This is an issue for all plotting functions `plot()`, `plot_quantile()`, etc.

> plot_quantile(acer_spectra, total_prob = 0.8, col = rgb(1, 0, 0, 0.25), border = FALSE, add=T)
Error in polygon(x = xx, y = yy, col = col, ...) : 
  plot.new has not been called yet

**Comment by meireles** [comment]
They do seem work fine. You cannot call any plotting function in R with with `add = T` if you haven't plotted anything before.  This is the typical error:

> plot.new has not been called yet

So you either need to add the plot *to an exiting plot* (with `add = T`) or use `add = F`. Here is an example:

```
s = as.spectra(spec_matrix_example)
plot(s)
plot_spec_regions(s, default_spec_regions(), add = T)

```

**Comment by annakat** [comment]
Funny, it doesn't seem to work when I run it from the vignette.

**Comment by meireles** [comment]
does it work from if you just load the package and execute the example above? I just tested it and it woks for me. 
It is possible that there's something funny with the vignette.

**Comment by annakat** [comment]
Yes, this works fine. Must be the vignette. Not urgent to find out what the problem is.

**Comment by meireles** [comment]
you're probably not evaluating something before the call. just a guess though
