### ISSUE TITLE
Subset wvl with decimal places

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#12]
Is there a way to use subset a spectra object when the wavelengths are "original", i.e. have decimal places? Would be nice to have.

**Comment by meireles** [comment]
yep, that already works

**Comment by annakat** [comment]
Getting single wavelengths works:
spec_sub <-  acer_spectra[ , c (484.3, 504.3)]

but wavelength regions does not: 
spec_sub <-  acer_spectra[ , 484.3 : 504.3]
Error in i_match_ij_spectra(this = this, i = i, j = j) : 
  Wavelength subscript out of bounds. Use wavelength labels instead of raw indices.
Called from: i_match_ij_spectra(this = this, i = i, j = j)

Am I doing something wrong?

**Comment by meireles** [comment]
maybe. you need to see if those wavelengths are labeled that way. use the `wavelength` function to get the vector of wavelength labels to check for that.

**Comment by annakat** [comment]
This is what I did and retrieving single wavelengths works: acer_spectra[ , c (484.3, 504.3)]...

**Comment by meireles** [comment]
The way to pick a spectral region without worrying about the exact wavelength labels is to use `wavelengths`'s `min` and `max` arguments :

    library(spectrolab)
    spec = as.spectra(spec_matrix_example)
    s = spec[ , wavelengths(spec, 400, 700) ]
