### ISSUE TITLE
structure of spectra object

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#15]
> str(aspen)
 $ G-IA2-2_000.sig  : num [1:358, 1:2001] 0.0469 0.0452 0.058 0.0554 0.0522 ...
 $ G-IA2-2_001.sig  : num [1:2001] 400 401 402 403 404 405 406 407 408 409 ...
 $ G-IA2-2_002.sig  : chr [1:358] "G-IA2-2_000.sig" "G-IA2-2_001.sig" 

could be $reflectance, $wavelengths, $samples

**Comment by meireles** [comment]
we need to think about this, but I don't see this being a problem. This weird behavior may actually help us... We do not want anyone (including ourselves) digging too much into the guts of a class.

**Comment by meireles** [comment]
So, I think that we should try to steer people away from gutting the class. check out cff2656437356f5c1cab77807824a174f3d7a56f
