### ISSUE TITLE
error message from spectra.R

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#16]
No spectra meet the criteria (reflectance < 0.2 @780nm), but error message doesn't make much sense. Should it be changed?
> xx <- excl_high(aspen, refl_high = 0.2, wvl_high = 780)
Error in i_reflectance(reflectance, nwavelengths = wl_l, nsample = spl_l,  : 
  Number of columns in x must be equal nwavelengths
Called from: i_reflectance(reflectance, nwavelengths = wl_l, nsample = spl_l, 
    enforce01 = enforce01)

**Comment by meireles** [comment]
Not sure what `excl_high` was doing, but the canonical way of testing a certain wavelength goes like this:

    library(spectrolab)
    spec = as.spectra(spec_matrix_example)
    keep = spec[ , 780] > 0.4

For now, we have to use `which` on the vector `keep` and subset based on that, but if should be easy to implement subsetting of samples based on a boolean vector. i.e.

    # this is what works
    spec[ which(keep),  ]

    # but this would be the ideal
    spec[keep, ]

**Comment by meireles** [comment]
see cb71d83acce385f52181f0f6f610f59d435cf912
