### ISSUE TITLE
plot normalized spectra generates warning message

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#17]
Has the warning to do with the metadata (here: normalized magn.)? 
Not a big deal, but would be prettier without it. 
 
> plot(spec_n[1:5])
Warning message:
In matrix(value, n, p) : data length exceeds size of matrix

**Comment by annakat** [comment]
When I add more metadata, all works fine and there is no warning anymore. Hmmm....

**Comment by meireles** [comment]
I guess that you forgot a comma. i.e. `spec_n[1:5, ]`

**Comment by annakat** [comment]
Same problem with the comma. When more metadata is added or when plotting the original spectra object (not VN) all is good.

**Comment by meireles** [comment]
I see. I'm changing the label to bug and will check this out later. Thx!

**Comment by meireles** [comment]
Fixed in commit bc7a3fd351eee3793fc76765fcba0bf934c352b6
