### ISSUE TITLE
design

### ISSUE THREAD

**Issue by meireles** [annakat/spectrolab#2]
@annakat Anna, we may want to talk tomorrow about the design of some of the functions and the API in general. We probably do not want to export too many functions, etc.

**Comment by annakat** [comment]
Can we talk Friday? I'm trying to make some progress with an analysis and thought about working from home.

**Comment by meireles** [comment]
Sure. I will not have much time tomorrow (or today), so I'll note some ideas here:

1. every function that operates on spectral data should take a spectra object, instead of a data frame or matrix. 

2. If a function's goal is to transform spectra, it must return a spectra object back (see normalize_spectra) for an example.

3. Functions should be as *general* as possible.  For instance: 
     * We should not assume that a wavelength will be a whole number. 
     * A function `do_something_spectra` must not assume that we're dealing with SVC. If it works on `spectra`, it should do so regardless of instrument.
     * We should avoid hard coding things, like the the min reflectance that identifies a bad spectrum.
     * Along the same lines, we do not want to impose onto the users how they should tag bad spectra. It should either be configurable or left for them to do prior to importing the files (only 2 lines of code).

4. we need to be careful not to bloat the namespace with too many functions. In general, less is more when it comes to APIs

So I think that the following changes would really improve usability:

* `read_spectra()`: reads a path and returns a `spectra` object.
* `jump_correction()`: takes a `spectra` object and returns a corrected `spectra` object
* `Preprocessing.R`: these functions should be wrapped into one function. The user can pick what kind of preprocessing they want. Conditions should not be hardcoded but set as defaults instead.
