### ISSUE TITLE
read.spectra PSR files with different settings

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#20]
I must have used different settings...
[122_4_D_PIRE_1_1_Y_00003.txt](https://github.com/annakat/spectrolab/files/741038/122_4_D_PIRE_1_1_Y_00003.txt)

result = i_read_ascii_spectra(i_path,
skip_first_n = 28,
sep_char = "\t",
wl_and_refl_cols = c(1, 2),
divide_refl_by = 100,
include_white_ref = include_white_ref,
outside_01_fun = fix_out01)

Your old parser is probably the better solution.

**Comment by meireles** [comment]
Maybe, but it will take a while to get it to work here. 

Anyways, I just looked at your file and it may be the case that you don't have the radiances because no foreoptic was set (line 14 -- Foreoptic: NONE   {DN}, NONE   {DN}).

The reflectance looks funny too. Are all your psr files like that?

**Comment by meireles** [comment]
Oh, and on my machine skipping 27 lines works fine. Did you manually change he file?

**Comment by annakat** [comment]
I didn't. I only changed the extension.

**Comment by meireles** [comment]
Ok, so maybe that one file is just weird then. Do you have radiances on the other ones?

**Comment by annakat** [comment]
Yeah, it's not the best example (it was actually in a "bad" folder). Here is one with
Foreoptic: FIBER1 {RADIANCE}
For me it's the same thing. It's Shan's data from last year. Funny that skipping 27 works for you. Did you change the file extension to .sed again? 

[30_5_D_PIST_1_2_M_00071.txt](https://github.com/annakat/spectrolab/files/741063/30_5_D_PIST_1_2_M_00071.txt)

**Comment by meireles** [comment]
Cool. Two things.

1- I didn't do anything to the file, just opened it. Line 27 is:" Wvl	Reflect. %", right?
2 - The problem isn't actually that hard to fix. I'll submit a patch in 5 min and you can test it.

**Comment by annakat** [comment]
1- For me L27 is "Data:". L28 is "Wvl Reflect. %"

**Comment by meireles** [comment]
that's messed up then. Can you paste the text itself here, as is?

**Comment by annakat** [comment]
Comment: 
Version: 2.2
File Name: C:\Documents and Settings\Administrator\My Documents\PSR\2015_JUL_24\2015_Jul_24\30_5_D_PIST_1_2_M_00071.sed
Instrument: PSR+3500_SN1566060 [3]
Detectors: 512,256,256
Measurement: REFLECTANCE
Date: 07/24/2015,07/24/2015
Time: 14:30:56.43,14:33:39.12
Temperature (C): 35.08,8.54,-5.10,35.72,8.54,-5.10
Battery Voltage: 6.81,6.79
Averages: 10,10
Integration: 20,32,10,50,50,10
Dark Mode: AUTO,AUTO
Foreoptic: FIBER1 {RADIANCE}, FIBER1 {RADIANCE}
Radiometric Calibration: RADIANCE
Units: W/m^2/sr/nm
Wavelength Range: 350,2500
Latitude: n/a
Longitude: n/a
Altitude: n/a
GPS Time: n/a
Satellites: n/a
Calibrated Reference Correction File: none
Channels: 2151
Columns [2]:
Data:
Wvl	Reflect. %
 350.0	    31.3872
 351.0	    29.0769
 352.0	    36.2507
 353.0	    37.8393
 354.0	    30.5828
 355.0	    30.0400
 356.0	    32.4579
 357.0	    32.4183
 358.0	    32.0423
 359.0	    31.6309
 360.0	    32.4643
 361.0	    34.0000
 362.0	    35.5777

**Comment by meireles** [comment]
I think that you see 28 lines here because the filename is wrapped. I.e. `File Name:` doesn't fit in one line. This is usually purely cosmetic (soft wrapping), but some editors can do "hard" wrapping.

Another possibility is that there is a funny character in the file name. Windows uses "\" as path separators, and those could cause issues. For instance, a new line in unix is "\n" and a tab "\t".

Will need to investigate this further tomorrow. When I paste the text in any of my editors (including R), "Wvl	Reflect. %" shows up in line 27...

**Comment by annakat** [comment]
Hm...I don't know. I didn't open the file at first, I read the original .sed. The data is on the shared drive, e.g. Dimensions/orig_data/FAB_2015/PSR+/JCB/07242015.

**Comment by meireles** [comment]
I have updated the parser. Try reinstalling the package and see if that solved the problem. Meanwhile I will check out the shared folder

**Comment by annakat** [comment]
Ok, interesting. I changed the default window width in my editor and see now "Wvl Reflect. %" in line 27 as you do. Skipping 27 is fine now, when the column indices are changed to 1 and 2.

**Comment by annakat** [comment]
I'll try the new parser in a sec.

**Comment by meireles** [comment]
That's what I said, many editors do the "soft wrap" thing. I took care of the column stuff, so things should work now.

**Comment by annakat** [comment]
Yes, everything works.
