### ISSUE TITLE
Help page for plot_regions

### ISSUE THREAD

**Issue by gross679** [annakat/spectrolab#22]
The plot_regions help page has a lot of helpful information, but, at some point, it may be good to reformat it. For instance, a good default set of regions ("spec_regions = cbind("VIS" = c(begin = 400, end = 700), "NIR" = c(begin = 800, end = 1300), "SWIR1" = c(begin = 1550, end = 1800), "SWIR2" = c(begin = 2000, end = 2400))" is given under Description, but could be moved further down. 

Also, the following produced a pretty set of region colors with the data plotted on top of them:
fun<-colorRampPalette(c("yellow","red"),alpha=0.9)
colors<-fun(4)

plot_regions(data,regions=spec_regions,col=colors,add=F,border=F,names=T)
plot_quantile(data,total_prob=0.5,add=T)

**Comment by annakat** [comment]
Thanks! The plot_regions help go an update, including the pretty colors as an example. I adjusted the transparency a bit, hope you still like it! 

For a simple plot of the default regions, you would typically do:
plot(data)
plot_regions(data, default_spec_regions(), add=T)
