### ISSUE TITLE
Undefined columns selected issue with .sed files

### ISSUE THREAD

**Issue by ShanKothari** [annakat/spectrolab#23]
I am using R 3.3.2 on Windows 8. When I try:

`dir_path = file.path("[my path]")`
`spectra = read_spectra(path=dir_path,format = "sed")`

I get the following error:

`Error in '[.data.frame'(read.delim(x, sep = sep_char, skip = skip_first_n,  : 
  undefined columns selected`

I'm attaching an example file because I suspect the issue has to do with the files themselves and not with specifying the path. (I've changed it to a .txt because GitHub won't accept .seds, but it should be readable as a .sed after changing the extension.)

[58_2G_QUMA_M_1.txt](https://github.com/annakat/spectrolab/files/745905/58_2G_QUMA_M_1.txt)

In person, Dudu suggested this error results from trouble dealing with the varying number of columns in Spectral Evolution files.

**Comment by meireles** [comment]
@ShanKothari Spectral Evolution doesn't make the life of parser writers easy... Both the number of data columns as well as their names can change. The scale of the reflectance data can also change ([0, 1] | [0, 100].

I have dealt with these issues now. *However, calling `read_spectra` on files with different formats will probably throw, which is not ideal.* 

Let me know if you can read your files now.

**Comment by ShanKothari** [comment]
Thanks Dudu! The function does work with the Spec Evo files now, and gives -- what appears to me on first glance -- appropriate output.

**Comment by meireles** [comment]
@ShanKothari cool. Just as a reference, the commit that fixed it was aaa91b9c712758c7fb0a27273be51c066963fb22
