### ISSUE TITLE
Error in resample() in Windows: 

### ISSUE THREAD

**Issue by bethfallon** [annakat/spectrolab#24]
When using resample() (in RStudio, Win 10, R 3.3.2), I get the following error:
`acer_resample<-resample(acer_spectra,new_wvls=c(400:2100))`
Error in parallel::mclapply(r, smooth.spline, x = w, nknots = nknots,  : 
  'mc.cores' > 1 is not supported on Windows

There is a suggestion on a possible fix here:
https://github.com/thibautjombart/adegenet/issues/109

**Comment by meireles** [comment]
@bethfallon thanks Beth, I'll fix that soon.

**Comment by meireles** [comment]
@bethfallon commit d26ac950d3b6e02cc358861e087aca2646a065d6 may have fixed it.

**Comment by bethfallon** [comment]
Yes, resample is working for me after the update. Thanks!

**Comment by meireles** [comment]
@bethfallon great! thx for reporting
