### ISSUE TITLE
read_spectra creates spectra object from files with different wavelengths 

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#29]
Read_spectra reads files with different wavelength when they are stored in the same folder, without causing an error. The wavelengths from the first file are kept. 

Figuring out which file-wavelengths match and which do not, and reorganizing the data would be a pain!

Maybe the following could work: 
- include a resampling option in read_spectra that doesn't care about increasing wavelengths
- in the case of different wvl: cause error message "wavelengths don't match. consider resampling"
- read_spectra (..., resample=...) reads and resamples 

example: download, rename .txt to .sig, and store in one folder: 
[27_G8_SUP_RUDSE__004.txt](https://github.com/annakat/spectrolab/files/769903/27_G8_SUP_RUDSE__004.txt)
[903_4_LIAAS_C_000.txt](https://github.com/annakat/spectrolab/files/769904/903_4_LIAAS_C_000.txt)

**Comment by meireles** [comment]
good catch! I was only testing for different number of bands. 42188cd7c1f130410a8e446b896e5911b5472dd7 solved it. 

The approach is the same as with diff number of bands. If a difference is detected, read spectra will return a list of spectra objects and will tell you that either the band number of wavelength values are incompatible.

**Comment by annakat** [comment]
great!! thanks!
