### ISSUE TITLE
combine doesn't like huge metadata 

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#30]
This is just a note: 
I accidentally added ~2000 columns of metadata to a spectra object A (metadata plus the original spectra). When I tried to combine spectra object A with spectra object B (both same wavelengths, and same first 10 metadata elements) it didn't work. There was no warning, but the metadata was printed (I think). 

last lines of output on screen
 `2395` = 0.0104214604245611, `2396` = 0.0103599210860154, 
        `2397` = 0.010297040373599, `2398` = 0.010231144167634, 
        `2399` = 0.0101671403634495, `2400` = 0.0101116073770042))

**Comment by meireles** [comment]
can you paste a minimum working example of what you were doing?

**Comment by meireles** [comment]
@annakat any thoughts? this seems to work perfectly for me, even merging two objects with 3200 spectra each and 5000 metadata columns.

**Comment by annakat** [comment]
I tried to make up an example, but it always worked. So here is a subset of the datasets that cause trouble: 

x <- read.table("~/Desktop/a1.txt", check.names = F)
y <- read.table("~/Desktop/b1.txt", check.names = F)
x <- as.spectra(x,name_idx = 1,meta_idxs = c(2:2015))
y <- as.spectra(y,name_idx = 1,meta_idxs = c(2:2015))
table(wavelengths(x)==wavelengths(y))
combine(x,y)

[a1.txt](https://github.com/annakat/spectrolab/files/772498/a1.txt)
[b1.txt](https://github.com/annakat/spectrolab/files/772499/b1.txt)

**Comment by meireles** [comment]
the problem is not the size of the metadata, but the names of the columns.
what is the error message after you `combine(x,y)`?

**Comment by annakat** [comment]
Ah, okay. So numbers are not allowed as column names? That's fine. There is no error message. I think the metadata gets printed after combine(x,y).

**Comment by meireles** [comment]
that is funny, I get an error message. what you see is part of the error message. it maybe clearer if you assign the result of the call, i.e. `z = combine(x, y)`.
anyhow, the issue is that numeric column names were getting changed internally. Try installing the version on my fork, i.e. install from `meireles/spectrolab` and see if that solves the issue. I'll merge it later.

**Comment by annakat** [comment]
It was a mistake anyway, I didn't want reflectances as metadata. I think usually metadata column names will start with letters.

**Comment by meireles** [comment]
sure, but using the latest version should work even with the mistake!
