### ISSUE TITLE
outside_01 extension 

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#31]
I'm wondering if it would be worth including an extended version of the outside_01_action of read_spectra(). 

The outside 0 part is not very useful for me, because every now and then spectra start with negative values although there are otherwise fine. But it would be nice not to read in spectra with reflectances that are substantially larger than 1, such as the noise spectrum attached (the lamp was off during the measurement). 

At the moment I'm subsetting noise spectra with:
y <- x[!rowSums(reflectance(x) > 1),]
which is not very intuitive. 

In addition, I'm wondering if read_spectra(outside_01_action = "NA") is actually working. The reflectance values of the noise spectrum I attached are kept when I do it. 
[noise.pdf](https://github.com/annakat/spectrolab/files/783832/noise.pdf)

**Comment by annakat** [comment]
Interesting:  read_spectra(outside_01_action = "NA") works when pointed directly to the noise file, or when the noise spectrum is the only file in a folder. But read_spectra(outside_01_action = "NA") does not work when there are more files in a folder. 
Attached some example spectra. "gr..." is the noise spectrum.

**Comment by meireles** [comment]
outside_01_action has been deprecated. 92ec171ade1045b8ee226e021114aa5320c3d21e
