### ISSUE TITLE
warning for match_sensors if factor is outside boundary

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#32]
Would be good if match_sensors() would give a warning, in cases when the matching factor needed to combine sensors is greater than a certain value. 

Example with Infinite values when match_overlap gets applied to noise file (attached). 

spec_match <- match_sensors (noise,c(990,1900))
Warning: feature under development!
match_sensors: should not be used in poduction code.
match_sensors: API will change.

Error in seq.default(y, y, length.out = length(s$sensor_3)) : 
  'from' cannot be NA, NaN or infinite
Called from: seq.default(y, y, length.out = length(s$sensor_3))

[noise.txt](https://github.com/annakat/spectrolab/files/784047/noise.txt)

**Comment by meireles** [comment]
Implemented. `match_sensors` on your noise file now returns "Conversion factors to match sensors 1 and 2 are outside of reasonable values for spectra: 1 "
