### ISSUE TITLE
Does normalize() accept metadata? 

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#33]
I'm not sure if I have normalized a spectra object with metadata before. But this is the first time I come across the issue that normalize doesn't like metadata. Removing metadata solves the problem, but is not ideal. Maybe I'm missing something. 

[testdat.txt](https://github.com/annakat/spectrolab/files/841916/testdat.txt)

test <- read.table("~/Desktop/testdat.txt", sep=",", check.names = F)
s <- as.spectra(test, name_idx = 1, meta_idxs = 2:5)
s_VN <- normalize(s)

Error message: 
Vector nomalizing spectra...
Note that y values will not be true reflectances anymore!
Trying to match by label...
Trying to match by index...
Error in i_match_label_or_idx(colnames(x$meta), label, full = TRUE, allow_empty_lookup = TRUE) : 
  No match.
Called from: i_match_label_or_idx(colnames(x$meta), label, full = TRUE, allow_empty_lookup = TRUE)

This works: 
s2 <- s
meta(s2) <- NULL
s2_VN <- normalize(s2)

**Comment by meireles** [comment]
This works fine for me. Do you still see this issue?

**Comment by meireles** [comment]
not sure what the issue was, but it seems that is has been fixed.
