### ISSUE TITLE
Can't read .sig files because of inclinometer metadata

### ISSUE THREAD

**Issue by elaliberte** [annakat/spectrolab#36]
In my .sig files, there are 27 header (metadata) lines. In your Acer example there are 25. The two additional ones in my files are:

inclinometer x offset= 0, 0
inclinometer y offset= 90, 90

This prevents data from being loaded by read_spectra().

If I delete these two inclinometer lines, it works.

**Comment by annakat** [comment]
The latest change should have fixed this problem for .sig files. Please try reinstalling spectrolab from GitHub with devtools::install_github("annakat/spectrolab"). Thanks!
